import asyncio
import os
import logging
from typing import Any, Dict, List
import mcp.types as types
from mcp.server import Server, NotificationOptions
from mcp.server.models import InitializationOptions
from mcp.server.stdio import stdio_server
from tavily import TavilyClient

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("tavily-mcp")

TAVILY_API_KEY = os.environ.get("TAVILY_API_KEY")
if not TAVILY_API_KEY:
    logger.warning("TAVILY_API_KEY not found in environment variables.")

server = Server("tavily-mcp")

@server.list_tools()
async def handle_list_tools() -> list[types.Tool]:
    return [
        types.Tool(
            name="tavily_search",
            description="Search the web for real-time information using Tavily API",
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "The search query"},
                    "search_depth": {
                        "type": "string", 
                        "enum": ["basic", "advanced"], 
                        "default": "basic",
                        "description": "The depth of the search"
                    },
                    "max_results": {
                        "type": "integer", 
                        "default": 5,
                        "description": "Maximum number of results to return"
                    },
                    "include_answer": {
                        "type": "boolean",
                        "default": False,
                        "description": "Include a short answer generated by LLM"
                    }
                },
                "required": ["query"]
            }
        )
    ]

@server.call_tool()
async def handle_call_tool(
    name: str, arguments: dict | None
) -> list[types.TextContent | types.ImageContent | types.EmbeddedResource]:
    
    if name != "tavily_search":
        raise ValueError(f"Unknown tool: {name}")

    if not arguments:
        raise ValueError("Missing arguments")

    if not TAVILY_API_KEY:
        return [types.TextContent(type="text", text="Error: TAVILY_API_KEY not configured.")]

    query = arguments.get("query")
    search_depth = arguments.get("search_depth", "basic")
    max_results = arguments.get("max_results", 5)
    include_answer = arguments.get("include_answer", False)

    try:
        tavily = TavilyClient(api_key=TAVILY_API_KEY)
        response = tavily.search(
            query=query,
            search_depth=search_depth,
            max_results=max_results,
            include_answer=include_answer
        )
        
        # Format the output
        result_text = ""
        
        if include_answer and "answer" in response:
            result_text += f"**Answer:** {response['answer']}\n\n"
            
        result_text += "**Search Results:**\n"
        for result in response.get("results", []):
            result_text += f"- **{result['title']}**\n"
            result_text += f"  {result['url']}\n"
            result_text += f"  {result['content'][:200]}...\n\n"
            
        return [types.TextContent(type="text", text=result_text)]

    except Exception as e:
        logger.error(f"Tavily search error: {e}")
        return [types.TextContent(type="text", text=f"Error executing search: {str(e)}")]

async def main():
    async with stdio_server() as (read, write):
        await server.run(
            read_stream=read,
            write_stream=write,
            initialization_options=InitializationOptions(
                server_name="tavily-mcp",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )

if __name__ == "__main__":
    asyncio.run(main())
